export const skills = [
  {
    label: "HTML5",
    value: "html5",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    color: "bg-orange-100 text-orange-600",
  },
  {
    label: "CSS3",
    value: "css3",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    color: "bg-blue-100 text-blue-600",
  },
  {
    label: "JavaScript",
    value: "javascript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    color: "bg-yellow-100 text-yellow-600",
  },
  {
    label: "TypeScript",
    value: "typescript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    color: "bg-blue-100 text-blue-700",
  },
  {
    label: "C++",
    value: "c++",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
    color: "bg-indigo-100 text-indigo-700",
  },
  {
    label: "Python",
    value: "python",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    color: "bg-yellow-100 text-blue-700",
  },
  {
    label: "Java",
    value: "java",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
    color: "bg-red-100 text-red-700",
  },
  {
    label: "React",
    value: "react",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    color: "bg-cyan-100 text-cyan-600",
  },
  {
    label: "Next.js",
    value: "nextjs",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    color: "bg-gray-100 text-gray-800",
  },
  {
    label: "Nuxt.js",
    value: "nuxtjs",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg",
    color: "bg-green-100 text-green-700",
  },
  {
    label: "Vue.js",
    value: "vuejs",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
    color: "bg-green-100 text-green-600",
  },
  {
    label: "Svelte",
    value: "svelte",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg",
    color: "bg-orange-100 text-orange-600",
  },
  {
    label: "Tailwind CSS",
    value: "tailwindcss",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
    color: "bg-cyan-100 text-cyan-700",
  },
  {
    label: "Bootstrap",
    value: "bootstrap",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg",
    color: "bg-purple-100 text-purple-700",
  },
  {
    label: "Material UI",
    value: "materialui",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg",
    color: "bg-blue-100 text-blue-600",
  },
  {
    label: "Git",
    value: "git",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    color: "bg-orange-100 text-orange-700",
  },
  {
    label: "GitHub",
    value: "github",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
    color: "bg-gray-100 text-gray-900",
  },
  {
    label: "VS Code",
    value: "vscode",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg",
    color: "bg-blue-100 text-blue-700",
  },
  {
    label: "Docker",
    value: "docker",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    color: "bg-sky-100 text-sky-700",
  },
  {
    label: "Firebase",
    value: "firebase",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
    color: "bg-amber-100 text-amber-600",
  },
  {
    label: "Mongo DB",
    value: "mongodb",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    color: "bg-green-100 text-green-700",
  },
  {
    label: "PostgreSQL",
    value: "postgresql",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
    color: "bg-blue-100 text-blue-700",
  },
  {
    label: "Drizzle",
    value: "drizzle",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/drizzle/drizzle-original.svg",
    color: "bg-blue-100 text-blue-700",
  },
  {
    label: "Opensearch",
    value: "opensearch",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/opensearch/opensearch-original.svg",
    color: "bg-indigo-100 text-indigo-700",
  },
  {
    label: "Shadcn",
    value: "shadcn",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/shadcn/shadcn-original.svg",
    color: "bg-gray-100 text-gray-700",
  },
  {
    label: "MQTT",
    value: "mqtt",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/mqtt/mqtt-original.svg",
    color: "bg-purple-100 text-purple-700",
  },
  {
    label: "Redis",
    value: "redis",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg",
    color: "bg-red-100 text-red-700",
  },
  {
    label: "GitLab",
    value: "gitlab",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg",
    color: "bg-orange-100 text-orange-600",
  },
  {
    label: "Debian",
    value: "debian",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/debian/debian-original.svg",
    color: "bg-red-100 text-red-700",
  },
  {
    label: "Linux",
    value: "linux",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
    color: "bg-yellow-100 text-yellow-700",
  },
  {
    label: "Zustand",
    value: "zustand",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/zustand/zustand-original.svg",
    color: "bg-teal-100 text-teal-700",
  },
  {
    label: "Zod",
    value: "zod",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/zod/zod-original.svg",
    color: "bg-purple-100 text-purple-700",
  },
  {
    label: "Next Auth",
    value: "nextauth",
    icon: "https://cdn.jsdelivr.net/gh/Gyosic/devicon/icons/nextauth/nextauth-original.svg",
    color: "bg-gray-100 text-gray-800",
  },
] as const;
